### PR TITLE
Fix/18 ssr issues

### LINKED ISSUE #18: SSR support
The intlProvider saga is a potential issue for SSR apps since in can be reused by multiple request handlers and can suffer from race conditions (overriding intl global var in the module).

### PR DESCRIPTION
**Pull request by jancama2**
Fixes #18 

I have used context api for redux saga. The context api has some limitations which result to breaking changes. Therefore this should be release in `5.*.*` version.

### CODE REVIEW

File: src/services/sagas/intlProvider.ts [hunk 1]
```diff
@@ -1,21 +1,44 @@
...
 export function* getIntl() {
-    if (!intl) {
-        const { payload } = yield take(types.SET_INTL);
-        return payload.intl;
+    const intlContext: IntlContextValueShape = yield getContext(SAGA_CONTEXT_KEY);
+    if (intlContext) {
+        const { intl } = intlContext;
+        return intl || null;
+    }
+    return null;
```
Comment (Tomas2D) [inline src/services/sagas/intlProvider.ts:31]: Could be simplified into a single line of code:

```
return intlContext?.intl ?? null;
```

**Review by cermakjiri — APPROVED** [review]
